//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace SMS.FeePaymentGrain.Class
{
    using Orleans.CodeGeneration;
    using Orleans;
    using System;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("SMS.FeePaymentGrain.Class.SMS.FeePaymentGrain.Class.FeePaymentGrain")]
    public class FeePaymentGrainState : global::Orleans.CodeGeneration.GrainState, FeePaymentState
    {
        

            public Guid @FeeID { get; set; }

            public Double @FeeAmount { get; set; }

            public String @FeeCode { get; set; }

            public DateTime @Date { get; set; }

            public String @StudentID { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("FeeID", out value)) @FeeID = (Guid) value;
                if (values.TryGetValue("FeeAmount", out value)) @FeeAmount = (Double) value;
                if (values.TryGetValue("FeeCode", out value)) @FeeCode = (String) value;
                if (values.TryGetValue("Date", out value)) @Date = (DateTime) value;
                if (values.TryGetValue("StudentID", out value)) @StudentID = (String) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("FeePaymentGrainState( FeeID={0} FeeAmount={1} FeeCode={2} Date={3} StudentID={4} )", @FeeID, @FeeAmount, @FeeCode, @Date, @StudentID);
            }
        
        public FeePaymentGrainState() : 
                base("SMS.FeePaymentGrain.Class.FeePaymentGrain")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["FeeID"] = this.FeeID;
            result["FeeAmount"] = this.FeeAmount;
            result["FeeCode"] = this.FeeCode;
            result["Date"] = this.Date;
            result["StudentID"] = this.StudentID;
            return result;
        }
        
        private void InitStateFields()
        {
            this.FeeID = default(Guid);
            this.FeeAmount = default(Double);
            this.FeeCode = default(String);
            this.Date = default(DateTime);
            this.StudentID = default(String);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            FeePaymentGrainState input = ((FeePaymentGrainState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            FeePaymentGrainState input = ((FeePaymentGrainState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            FeePaymentGrainState result = new FeePaymentGrainState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
